language: node_js
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - npm install --global yarn --cache-min 999999999
install:
  - yarn
script:
  - yarn test
env:
- CXX=g++-4.8
deploy:
  skip_cleanup: true
  provider: script
  script: yarn run deploy
  on:
    branch: master
